trailingComma": 'es5'
tabWidth: 4
semi: false
singleQuote: true
printWidth: 80
prose-wrap: always
overrides:
  - files: '*.md'
    options:
      tabWidth: 2
  - files: '*.{yml,yaml}'
    options:
      tabWidth: 2
