language: nix
nix: 2.2.2
sudo: required
branches:
  only:
  - source

before_install:
  - nix-channel --update
  - nix-env --upgrade --always
# See: https://github.com/travis-ci/travis-ci/issues/7995#issuecomment-313169701
before_deploy: sudo chown -R travis:travis /home/travis/

script:
- set -e
- nix-build release.nix

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: ./result
  verbose: true
  on:
    branch: source
