# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ source ]
  push:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - uses: cachix/cachix-action@v5
      with:
        name: cv-maxdaten-io
        attributes: pages
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build release.nix
    - name: Upload pages
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pages
        path: result
