name: CI

on:
  pull_request:
    branches: [source]
  push:
    branches: [source]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v13

      - uses: cachix/cachix-action@v10
        with:
          name: brutal-recipes
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build release.nix

      - name: Artifact pages
        uses: actions/upload-artifact@v2
        with:
          name: pages
          path: result
          if-no-files-found: error
  deploy:
    if: github.ref == 'refs/heads/source'
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: pages
          path: result
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.4.0
        with:
          build_dir: result
          target_branch: master
          keep_history: 'true'
          fqdn: brutal-recipes.maxdaten.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
